- name: My first play
  hosts: localhost # Run on local machine
  tasks:
    # Test connectivity to the host
    - name: Ping my hosts
      ansible.builtin.ping:

    # Print a static hello world message to stdout
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world