- name: My first play
  hosts: localhost
  tasks:
    # Ping task to check connectivity
    - name: Ping my hosts
      ansible.builtin.ping:

    # Debug message task
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world
