- name: My first play
  hosts: localhost
  # Define the tasks to be executed
  tasks:
    # Ensure connectivity to the host
    - name: Ping my hosts
      ansible.builtin.ping:

    # Output a debug message
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world