- name: My first play
  hosts: localhost
  tasks:
    # Check connectivity to the host
    - name: Ping my hosts
      ansible.builtin.ping:

    # Output a simple debug message
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world