- name: Variables playbook tests
  hosts: localhost
  vars:
    debug_message: "Hello world"
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: "{{ debug_message }}"